[versions]
dagger = "2.42"
nav = "2.5.1"

[libraries]
dagger2-dagger = { module = "com.google.dagger:dagger", version.ref = "dagger" }
dagger2-compiler = { module = "com.google.dagger:dagger-compiler", version.ref = "dagger" }

timber = "com.jakewharton.timber:timber:5.0.1"

utils-viewBindingDelegate = "com.github.kirich1409:viewbindingpropertydelegate-noreflection:1.5.6"

nav-fragment = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "nav" }
nav-ui = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "nav" }
nav-args = { module = "androidx.navigation:navigation-safe-args-gradle-plugin", version.ref = "nav" }

[plugins]
jvm = "org.jetbrains.kotlin.jvm:1.7.10"